# Compiles contracts and runs prepare-deploy, enabling latest release contracts for deployment
parameters:
  network:
    type: string
steps:
  - run: node publish build
  - run: node publish prepare-deploy --network << parameters.network >>
  - persist_to_workspace:
      root: .
      paths:
        - build
        - publish/deployed
