# Restarts a forked chain, and runs production tests with gas reports against it
description: Runs prod tests on a fork
parameters:
  network:
    type: string
steps:
  - cmd-fork-start:
      network: << parameters.network >>
  - run: npm run test:prod:gas && npx codechecks codechecks.prod.yml
  - store_artifacts:
      path: test-gas-used-prod.log
