# Restarts a forked chain, and runs production tests with gas reports against it
{{> job-header.yml}}
parameters:
  network:
    type: string
steps:
  - checkout
  - attach_workspace:
      at: .
  - cmd-fork-start:
      network: << parameters.network >>
  - run: npm run test:prod:gas && npx codechecks codechecks.prod.yml
  - store_artifacts:
      path: test-gas-used-prod.log
