# Restarts a forked chain, and runs production tests with gas reports against it
working_directory: ~/repo
docker:
  - image: circleci/node:12.18
parameters:
  network:
    type: string
steps:
  - checkout
  - attach_workspace:
      at: .
  - cmd-production-tests:
      network: << parameters.network >>
