# Starts a forked chain, and runs the deploy command against it
working_directory: ~/repo
docker:
  - image: circleci/node:12.18
parameters:
  network:
    type: string
steps:
  - checkout
  - attach_workspace:
      at: .
  - cmd-forked-deploy:
      network: << parameters.network >>
