# Compiles all contracts and fails with oversized contracts
{{> job-header.yml}}
steps:
  - checkout
  - attach_workspace:
      at: .
  - run: npx buidler compile --optimizer --fail-oversize
  - run: npx buidler compile --use-ovm --optimizer --fail-oversize
