# Validates that sources have been verified in etherscan
working_directory: ~/repo
docker:
  - image: circleci/node:12.18
parameters:
  network:
    type: string
steps:
  - checkout
  - attach_workspace:
      at: .
  - cmd-etherscan-check:
      network: << parameters.network >>
